LICENSE
Currently the project doesn't have a license defined, i propose use MIT license because of permissive permissions.
=> License MIT attached

.github/workflows/main.yml
CI CD pipelines working in github actions.
=> CI CD Pipelines

async/async-commons-starter/src/main/java/org/reactivecommons/async/impl/config/RabbitMqConfig.java
fix #35
This mitigates the problem but can be considered as a workaround, should we report to reactor-rabbit?
=> fix: set resourceManagementChannelMono from channelPool

README.md, async/async-commons-api/src/main/java/org/reactivecommons/async/api/HandlerRegistry.java, async/async-commons-starter/src/main/java/org/reactivecommons/async/impl/config/MessageListenersConfig.java, async/async-commons-starter/src/main/java/org/reactivecommons/async/impl/config/props/AsyncProps.java, async/async-commons-starter/src/main/java/org/reactivecommons/async/impl/config/props/BrokerConfigProps.java, async/async-commons-starter/src/main/java/org/reactivecommons/async/impl/config/props/NotificationProps.java, async/async-commons/src/main/java/org/reactivecommons/async/impl/HandlerResolver.java, async/async-commons/src/main/java/org/reactivecommons/async/impl/listeners/ApplicationNotificationListener.java, async/async-commons/src/main/java/org/reactivecommons/async/impl/utils/NameGenerator.java, async/async-commons/src/test/java/org/reactivecommons/async/impl/DynamicRegistryImpTest.java, gradle.properties
Adds notification event listener to message listener config
Adds configuration variables and utils method
updates version
modifies read me to add listener exampel
modifies read me to add listener example
modifies read me to add listener example
=> Adds event notification listener

.github/workflows/main.yml, README.md, async/async-commons/src/test/java/org/reactivecommons/async/impl/RabbitDirectAsyncGatewayTest.java, build.gradle
- Add some unit test for `RabbitDirectAsyncGateway`
- Exclude `samples` from code coverage
=> Feature unit tests

async/async-commons-api/src/main/java/org/reactivecommons/async/api/DynamicRegistry.java, async/async-commons-api/src/main/java/org/reactivecommons/async/api/HandlerRegistry.java, async/async-commons-api/src/test/java/org/reactivecommons/async/api/HandlerRegistryTest.java, async/async-commons-starter/src/main/java/org/reactivecommons/async/impl/config/RabbitMqConfig.java, async/async-commons/src/main/java/org/reactivecommons/async/impl/DynamicRegistryImp.java, async/async-commons/src/main/java/org/reactivecommons/async/impl/HandlerResolver.java, async/async-commons/src/main/java/org/reactivecommons/async/impl/listeners/ApplicationEventListener.java, async/async-commons/src/test/java/org/reactivecommons/async/impl/DynamicRegistryImpTest.java, async/async-commons/src/test/java/org/reactivecommons/async/impl/listeners/ApplicationCommandListenerPerfTest.java, async/async-commons/src/test/java/org/reactivecommons/async/impl/listeners/ApplicationQueryListenerTest.java, async/async-commons/src/test/java/org/reactivecommons/async/impl/listeners/ListenerReporterTestSuperClass.java
=> feat: dynamic events handlers

.github/workflows/main.yml, async/async-commons-api/async-commons-api.gradle, async/async-commons-standalone/async-commons-standalone.gradle, async/async-commons-starter/async-commons-starter.gradle, async/async-commons/async-commons.gradle, build.gradle, domain/domain-events/domain-events-api.gradle, gradle.properties, main.gradle, settings.gradle
- Update gradle build files for release in maven central, extract common tasks to the main.gradle file.
=> Publish to maven central

async/async-commons/src/main/java/org/reactivecommons/async/commons/Headers.java, async/async-rabbit-starter/src/main/java/org/reactivecommons/async/rabbit/config/QueryListenerConfig.java, async/async-rabbit-starter/src/main/java/org/reactivecommons/async/rabbit/config/props/DirectProps.java, async/async-rabbit/src/main/java/org/reactivecommons/async/rabbit/RabbitDirectAsyncGateway.java, async/async-rabbit/src/main/java/org/reactivecommons/async/rabbit/listeners/ApplicationQueryListener.java, async/async-rabbit/src/main/java/org/reactivecommons/async/rabbit/listeners/GenericMessageListener.java, async/async-rabbit/src/test/java/org/reactivecommons/async/rabbit/listeners/ApplicationQueryListenerErrorTest.java, async/async-rabbit/src/test/java/org/reactivecommons/async/rabbit/listeners/ApplicationQueryListenerTest.java
=> Discard timeout queries

async/async-rabbit/src/main/java/org/reactivecommons/async/rabbit/converters/json/JacksonMessageConverter.java, async/async-rabbit/src/test/java/org/reactivecommons/async/rabbit/converters/json/JacksonMessageConverterTest.java, gradle.properties
Features
- Charset conversion based on sender charset header.
=> add charset conversion when reading message body

async/async-rabbit-starter/src/main/java/org/reactivecommons/async/rabbit/config/RabbitMqConfig.java
Features:
- Enable ssl using `spring.rabbitmq.ssl.enabled` property in the default ConnectionFactoryProvider bean
=> Enable ssl using spring.rabbitmq.ssl.enabled property

async/async-commons-api/src/main/java/org/reactivecommons/async/api/DynamicRegistry.java, async/async-commons-api/src/main/java/org/reactivecommons/async/api/HandlerRegistry.java, async/async-commons-api/src/test/java/org/reactivecommons/async/api/HandlerRegistryTest.java, async/async-rabbit-starter/src/main/java/org/reactivecommons/async/rabbit/config/RabbitMqConfig.java, async/async-rabbit/src/main/java/org/reactivecommons/async/rabbit/DynamicRegistryImp.java, async/async-rabbit/src/main/java/org/reactivecommons/async/rabbit/HandlerResolver.java, async/async-rabbit/src/main/java/org/reactivecommons/async/rabbit/listeners/ApplicationEventListener.java, async/async-rabbit/src/test/java/org/reactivecommons/async/rabbit/DynamicRegistryImpTest.java, async/async-rabbit/src/test/java/org/reactivecommons/async/rabbit/listeners/ApplicationCommandListenerPerfTest.java, async/async-rabbit/src/test/java/org/reactivecommons/async/rabbit/listeners/ApplicationQueryListenerTest.java, async/async-rabbit/src/test/java/org/reactivecommons/async/rabbit/listeners/ListenerReporterTestSuperClass.java, gradle.properties
Features:
- Remove event listener and dynamic event listener distinction from handler resolver.
=> Event listeners unification

async/async-rabbit/src/main/java/org/reactivecommons/async/rabbit/listeners/ApplicationQueryListener.java, async/async-rabbit/src/test/java/org/reactivecommons/async/rabbit/listeners/ApplicationQueryListenerTest.java
=> fix: propagate empty response

async/async-rabbit/src/main/java/org/reactivecommons/async/rabbit/RabbitDirectAsyncGateway.java
Add metric for query request to an external source
=> add metric to async query operation

async/async-commons-api/src/main/java/org/reactivecommons/async/api/DirectAsyncGateway.java, async/async-rabbit-starter-eda/src/main/java/org/reactivecommons/async/rabbit/config/CommandListenersConfig.java, async/async-rabbit-starter-eda/src/main/java/org/reactivecommons/async/rabbit/config/props/AsyncProps.java, async/async-rabbit-starter/src/main/java/org/reactivecommons/async/rabbit/config/CommandListenersConfig.java, async/async-rabbit-starter/src/main/java/org/reactivecommons/async/rabbit/config/props/AsyncProps.java, async/async-rabbit/src/main/java/org/reactivecommons/async/rabbit/RabbitDirectAsyncGateway.java, async/async-rabbit/src/main/java/org/reactivecommons/async/rabbit/communications/ReactiveMessageSender.java, async/async-rabbit/src/main/java/org/reactivecommons/async/rabbit/communications/TopologyCreator.java, async/async-rabbit/src/main/java/org/reactivecommons/async/rabbit/listeners/ApplicationCommandListener.java, async/async-rabbit/src/test/java/org/reactivecommons/async/rabbit/listeners/ApplicationCommandListenerPerfTest.java, async/async-rabbit/src/test/java/org/reactivecommons/async/rabbit/listeners/ApplicationCommandListenerTest.java, gradle.properties, samples/async/receiver-responder/src/main/java/sample/SampleReceiverApp.java, samples/async/receiver-responder/src/main/resources/application.yaml, samples/async/sender-client/src/main/java/sample/SampleRestController.java
=> Add delayed command capability

async/async-rabbit-starter-eda/src/main/java/org/reactivecommons/async/rabbit/config/RabbitMqConfig.java, async/async-rabbit-starter-eda/src/main/java/org/reactivecommons/async/rabbit/config/props/AsyncProps.java, async/async-rabbit-starter-eda/src/main/java/org/reactivecommons/async/rabbit/config/props/AsyncPropsDomain.java, gradle.properties
Features:
- Add option to fill async props with any secret provider using a callback
=> Fill with secret

async/async-rabbit-starter-eda/async-commons-rabbit-starter-eda.gradle, async/async-rabbit-starter-eda/src/main/java/org/reactivecommons/async/rabbit/config/EventListenersConfig.java, async/async-rabbit-starter-eda/src/main/java/org/reactivecommons/async/rabbit/config/props/AsyncPropsDomain.java, async/async-rabbit-starter-eda/src/main/java/org/reactivecommons/async/rabbit/config/props/DomainProps.java, gradle.properties
Features:
- Allow disable event listener for specific domain in EDA variant
=> Add option to disable event listener

main.gradle
=> fix(ci): Fix release

docs/docs/reactive-commons-eda/4-configuration-properties.md, docs/docs/reactive-commons/6-handling-domain-events.md, docs/docs/reactive-commons/9-configuration-properties.md
docs(wildcard): Update documentation with changes in retries and wildcards
=> docs(wildcard): Update documentation with changes in retries and wildcards

async/async-rabbit/src/main/java/org/reactivecommons/async/rabbit/listeners/GenericMessageListener.java, docs/docs/reactive-commons/10-wildcards.md, samples/async/async-receiver-responder/src/main/java/sample/HandlersConfig.java, samples/async/async-receiver-responder/src/main/resources/application.yaml
=> fix(retries): local retries

async/async-rabbit-starter-eda/src/main/java/org/reactivecommons/async/rabbit/config/ConnectionManager.java, async/async-rabbit-starter-eda/src/main/java/org/reactivecommons/async/rabbit/config/RabbitMqConfig.java
Each discard notifier will have the connections properties of the specific domain
=> fix(notifier): Set the discard notifier with domain connection properties

starters/async-kafka-starter/src/main/java/org/reactivecommons/async/kafka/annotations/EnableEventListeners.java, starters/async-kafka-starter/src/main/java/org/reactivecommons/async/kafka/annotations/EnableNotificationListener.java, starters/async-kafka-starter/src/main/java/org/reactivecommons/async/kafka/config/RCKafkaConfig.java, starters/async-kafka-starter/src/main/java/org/reactivecommons/async/kafka/config/RCKafkaEventListenerConfig.java, starters/async-kafka-starter/src/main/java/org/reactivecommons/async/kafka/config/RCKafkaHandlersConfiguration.java
Fix kafka starter to allow only sender
=> chore(next): Fix kafka starter

gradle.properties, starters/async-rabbit-starter/src/main/java/org/reactivecommons/async/rabbit/RabbitMQSetupUtils.java
Add default SSLContext when ssl is enabled
=> feat(tls): ssl default options

build.gradle, main.gradle
This PR updates dependencies to latest versions
=> fix(deps): update dependencies

build.gradle, main.gradle
This PR updates dependencies to latest versions
=> chore(deps): update dependencies
